### ISSUE TITLE
Featured Lodgings on the Booking page should be clickable

### ISSUE THREAD

**Issue by dakatk** [rvtr/rvtrx-campground#66]
The Featured Lodgings cards displayed on the Booking page should take the user to the specified lodging's details when clicks. These cards should also have either more details present directly on the card, or a few more details that are accessible from a drop-down element/from hovering the mouse over the card itself.

**Comment by DevJamesC** [comment]
---Trello Card Description---
When we click on the featured card, it routes to the lodging detail.

Card has:
image of location, 
name of location, 
State/Province/City and Country

Card should have highlight effects.

Conform Size and Format.
